# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.4
#
# <auto-generated>
#
# Generated from file `visa_device.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy
import device_repo_ice.device_repo_ice

# Included module device_repo_ice
_M_device_repo_ice = Ice.openModule('device_repo_ice')

# Start of module device_repo_ice
__name__ = 'device_repo_ice'

_M_device_repo_ice._t_VisaDevice = IcePy.defineValue('::device_repo_ice::VisaDevice', Ice.Value, -1, (), False, True, None, ())

if 'VisaDevicePrx' not in _M_device_repo_ice.__dict__:
    _M_device_repo_ice.VisaDevicePrx = Ice.createTempClass()
    class VisaDevicePrx(_M_device_repo_ice.DevicePrx):

        def visa_query(self, context=None):
            return _M_device_repo_ice.VisaDevice._op_visa_query.invoke(self, ((), context))

        def visa_queryAsync(self, context=None):
            return _M_device_repo_ice.VisaDevice._op_visa_query.invokeAsync(self, ((), context))

        def begin_visa_query(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_device_repo_ice.VisaDevice._op_visa_query.begin(self, ((), _response, _ex, _sent, context))

        def end_visa_query(self, _r):
            return _M_device_repo_ice.VisaDevice._op_visa_query.end(self, _r)

        def visa_write(self, context=None):
            return _M_device_repo_ice.VisaDevice._op_visa_write.invoke(self, ((), context))

        def visa_writeAsync(self, context=None):
            return _M_device_repo_ice.VisaDevice._op_visa_write.invokeAsync(self, ((), context))

        def begin_visa_write(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_device_repo_ice.VisaDevice._op_visa_write.begin(self, ((), _response, _ex, _sent, context))

        def end_visa_write(self, _r):
            return _M_device_repo_ice.VisaDevice._op_visa_write.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_device_repo_ice.VisaDevicePrx.ice_checkedCast(proxy, '::device_repo_ice::VisaDevice', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_device_repo_ice.VisaDevicePrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::device_repo_ice::VisaDevice'
    _M_device_repo_ice._t_VisaDevicePrx = IcePy.defineProxy('::device_repo_ice::VisaDevice', VisaDevicePrx)

    _M_device_repo_ice.VisaDevicePrx = VisaDevicePrx
    del VisaDevicePrx

    _M_device_repo_ice.VisaDevice = Ice.createTempClass()
    class VisaDevice(_M_device_repo_ice.Device):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::device_repo_ice::Device', '::device_repo_ice::VisaDevice')

        def ice_id(self, current=None):
            return '::device_repo_ice::VisaDevice'

        @staticmethod
        def ice_staticId():
            return '::device_repo_ice::VisaDevice'

        def visa_query(self, current=None):
            raise NotImplementedError("servant method 'visa_query' not implemented")

        def visa_write(self, current=None):
            raise NotImplementedError("servant method 'visa_write' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_device_repo_ice._t_VisaDeviceDisp)

        __repr__ = __str__

    _M_device_repo_ice._t_VisaDeviceDisp = IcePy.defineClass('::device_repo_ice::VisaDevice', VisaDevice, (), None, (_M_device_repo_ice._t_DeviceDisp,))
    VisaDevice._ice_type = _M_device_repo_ice._t_VisaDeviceDisp

    VisaDevice._op_visa_query = IcePy.Operation('visa_query', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), _M_device_repo_ice._t_strings, False, 0), ())
    VisaDevice._op_visa_write = IcePy.Operation('visa_write', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())

    _M_device_repo_ice.VisaDevice = VisaDevice
    del VisaDevice

# End of module device_repo_ice
